### ISSUE TITLE
data organizing

### ISSUE THREAD

**Issue by zyune** [ds5010/broadband#4]
<img width="524" alt="Screen Shot 2022-04-18 at 9 11 38 PM" src="https://user-images.githubusercontent.com/66234261/163900933-7815ac59-967e-4e95-8eec-e86ec03a6b23.png">

**Comment by sophiacofone** [comment]
Hi Data team @zyune @MatthewjRay @kayneryan,

Our task is to organize the repo by county and report type. The code should be reproducible and well documented to support the organization. Yune's picture above shows what the organization should look like. Each county name will be a directory that will contain all the different layer geojson files per that county. 

After chatting with Yune just now we decided that [Yune's code](https://github.com/ds5010/broadband/issues/3) is already most of the way there, we just need to make 2 small modifications. First, we need to incorporate the other data file layers into the code, or provide an option for that to be a parameter. Then, we need to change the file naming convention at the end so that all output files are named relevant to the data layer (rather than just all being the county name). Does this sound like a good plan?

**Comment by MatthewjRay** [comment]
@zyune @sophiacofone @kayneryan 

This structure looks good, and the next steps outlined seem logical. Here is a link to the tier data segmented by County that I put together.  Please take a look and make sure it looks accurate. If we need any additional segments for this dataset, let me know, and I can work on it tomorrow. 

https://github.com/MatthewjRay/5010_Data/tree/main/broadband_tiers_county_data

**Comment by sophiacofone** [comment]
@zyune @MatthewjRay I made a pull request addressing this, please let me know if it is what you guys were thinking. Thanks!

**Comment by sophiacofone** [comment]
Also sorry to all for the rouge merge to main branch! Completely my bad, I think I restored it to what it was before (keeping the mistake in the history) but please let me know if I did that wrong.
